---
- name: "Config wartch of mashines"
  hosts: localhost
  become: yes
  tasks:
   - name: Git Clone
     git:
      repo: https://github.com/andgabs/skill_hmao
      dest: /skill_hmao
      clone: yes

   - name: Decrypt Users File
     shell: ansible-vault decrypt --vault-id /skill_hmao/hmao-yarulin/password /skill_hmao/Users/privvars.yml

   - name: Add Debian Hosts
     add_host:
       hostname: '{{ item }}'
       groups: Debian
       ansible_ssh_user: root
       ansible_ssh_pass: toor
       ansible_host_key_checking: false
     loop:
     - PJD-01
     - PJD-02

   - name: Add CentOS Hosts
     add_host:
       hostname: '{{ item }}'
       groups: Centos
       ansible_ssh_user: root
       ansible_ssh_pass: toor
       ansible_host_key_checking: false
     loop:
     - PJC-01
     - PJC-02

- name: update cache and isntall package
  hosts: all
  tasks:
   - name: Test Connection
     ping:

   - name: Update Debian
     apt: 
       update_cache: true
     when: "'Debian' in group_names"

   - name: Update CentOS
     yum: 
       update_cache: true
     when: "'Centos' in group_names"

   - name: "Include Vars From software.yaml"
     include_vars: /skill_hmao/software.yaml

   - name: "Install software from file for Debian"
     apt:
      name: "{{ software }}"
      update_cache: yes
     when: "'Debian' in group_names"

   - name: "Install software from file for Centos"
     yum:
      name: "{{ software }}"
      update_cache: yes
     when: "'Centos' in group_names"

   - name: Include Vars From privvars.yml
     include_vars:
        file: /skill_hmao/Users/privvars.yml

   - name: Add Usres From privvars.yml
     user:
        name: "{{ item.0 }}"
        password: "{{ item.1 | password_hash('sha512')}}"
     with_together:
         - "{{ skillcloud.users }}"
         - "{{ skillcloud.passwords }}"

   - name: add authorized key to user
     authorized_key:
        user: "{{ item.0 }}"
        state: present
        key: "{{ skillcloud.publickey }}"
     with_together:
        - "{{ skillcloud.users }}"

   - name: Install Debian
     apt: 
      name: "{{ item }}"
     loop:
         - docker
         - docker-compose
         - firewalld
         - nginx
     when: "'Debian' in group_names"

   - name: Install CentOS
     yum: 
      name: "{{ item }}"
     loop:
         - firewalld
         - nginx
     when: "'Centos' in group_names"

   - name: Firewalld Enable
     service:
        name: firewalld
        state: started
        enabled: yes

   - name: Firewalld Port
     firewalld:
         zone: public
         port: "{{ item }}"
         permanent: true
         immediate: true
         state: enabled
     loop:
         - 80/tcp
         - 8080/tcp
         - 1022/tcp

   - name: Configure SSH server
     lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
     loop:
        - { regexp: '^#?#Port.*', line: 'Port 1022' }
        - { regexp: '^#?#PubkeyAuthentication.*', line: 'PubkeyAuthentication yes' }

   - name: copy sh script
     copy:
        src: /skill_hmao/docker-compose.sh
        dest: /

   - name: run docker sh script
     shell: sh /docker-compose.sh

   - name: add docker repo
     shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
     when: "'Centos' in group_names"

   - name: install docker-ce on Centos
     yum:
        name: docker-ce
     when: "'Centos' in group_names"

   - name: "Enable and start docker"
     systemd:
        name: docker
        state: started
        enabled: true
     when: "'Centos' in group_names"

   - name: "Copy to skillcloud-nginx"
     copy:
        src: /skill_hmao/{{ item }}
        dest: /skillcloud-nginx/{{ item }}
        remote_src: yes
     with_items:
        - docker-compose.sh
        - docker-compose.yml
        - dockerfile-balance
        - dockerfile-site
        - index.html
        - nginx.conf
     when: "'Centos' in group_names"

   - name: Build Image Balance
     docker_image:
        path: /skillcloud-nginx/balance
        name: balance
        tag: balance
     when: "'Centos' in group_names"

   - name: Build Image Site
     docker_image:
        path: /skillcloud-nginx/site
        name: site
        tag: site
     when: "'Centos' in group_names"

   - name: docker-compose up
     shell:
        cmd: docker-compose -f docker-compose.yml up -d
        chdir: /skillcloud-nginx
     when: "'Centos' in group_names"

   - name: Restart Firewalld
     service:
        name: firewalld
        state: restarted

   - name: Restart ssh/sshd
     service:
        name: "{{ item }}"
        state: restarted
     loop:
         - ssh
         - sshd

   - name: "Rebiit nachines"
     reboot:
