---
- name: "Config wartch of mashines"
  hosts: localhost
  become: yes
  tasks:
   - name: Add Hosts
     add_host:
       hostname: '{{ item.hostname }}'
       groups: '{{ item.groups }}'
       ansible_ssh_port: 22
       ansible_ssh_private_key_file: /opt/keys/'{{ item.hostname }}'.key
     with_items:
     - {hostname: alt, groups: ALT}
     - {hostname: redos, groups: REDOS}
     - {hostname: astra, groups: ASTRA}
