---
- name: "Config wartch of mashines"
  hosts: localhost
  become: yes
  tasks:
   - name: Create inventory
     file:
       path: /opt/ansible/hosts
       state: touch
    
   - name: Add Hosts
     blockinfile:
       path: /opt/ansible/hosts
       block: |
         [ALT]
         alt ansible_ssh_private_key_file:/opt/keys/alt.key

         [REDOS]
         redos ansible_ssh_private_key_file:/opt/keys/redos.key

         [ASTRA]
         astra ansible_ssh_private_key_file:/opt/keys/astra.key
         
         [Servers:children]
         ALT
         ASTRA
         REDOS
