---
- name: "Config wartch of mashines"
  hosts: localhost
  become: yes
  tasks:
   - name: Create inventory
     file:
       path: /opt/ansible/hosts
       state: touch
    
   - name: Add Hosts
     blockinfile:
       path: /opt/ansible/group_vars/all
       block: |
       ['{{ item.groups }}']
       hostname: '{{ item.hostname }}' ansible_ssh_private_key_file: /opt/keys/'{{ item.hostname }}'.key
     with_items:
     - {hostname: alt, groups: ALT}
     - {hostname: redos, groups: REDOS}
     - {hostname: astra, groups: ASTRA}

   - name: Add Servers Hosts
     add_host:
       hostname: '{{ item.hostname }}'
       groups: "Servers:children"
     loop:
     - ALT
     - ASTRA
     - REDOS
