---
- name: "Config wartch of mashines"
  hosts: localhost
  become: yes
  tasks:
   - name: Create inventory
     file:
       path: /opt/ansible/hosts
       state: touch

   - name: Configure inventory server
     lineinfile:
       path: /etc/ansible/ansible.cfg
       regexp: #?#inventory.*
       line: inventory = /etc/ansible/hosts
       state: present
       
   - name: Add Hosts
     blockinfile:
       path: /opt/ansible/hosts
       block: |
         [ALT]
         alt ansible_ssh_private_key_file:/opt/keys/alt.key

         [REDOS]
         redos ansible_ssh_private_key_file:/opt/keys/redos.key

         [ASTRA]
         astra ansible_ssh_private_key_file:/opt/keys/astra.key
         
         [Servers:children]
         ALT
         ASTRA
         REDOS

   - name: Create directory for group_vars
     file:
       path: /opt/ansible/group_vars
       state: directory

   - name: Create config
     file:
       path: /opt/ansible/group_vars/all
       state: touch

   - name: Configure group_vars
     blockinfile:
       path: /opt/ansible/group_vars/all
       block: |
         ansible_user: sshuser
         ansible_host_key_checking: false
         ansible_ssh_private_key_file: /opt/keys/{{ inventory_hostname }}
         ansible_python_interpreter: /usr/bin/python3

   - name: "Config mashines"
     hosts: all
     become: yes
     tasks:
       - name: Test Connection
         ping:
